# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Vmmt5-TEeG7R_xBsMMV6nRhSzwVr85z
"""

import pandas as pd
import matplotlib.pyplot as plt

df1 = pd.read_csv('spotify_top50_2021.csv')

df1.head(5)

#1
df1.sort_values(by ='id', ascending = True)

#importando imagem grafico
p = df1['popularity']
t = df1['tempo']
plt.bar( p, t, color = 'red', lw= 20 )

na = df1['artist_name']
t = df1['tempo']
plt.bar( na, t, color = 'red', lw= 20 )